### ISSUE TITLE
Arquivo oldSigner.php na pasta e carregado indevidamente

### ISSUE THREAD

**Issue by rafaelmb** [nfephp-org/sped-nfse-ipm#14]
O arquivo oldSigner do diretório vendor/nfephp-org/sped-nfse-ipm/src/Common/oldSigner.php fez o composer se perder pois ambos (Signer.php e oldSigner.php) tem o mesmo nome de  classe.

* **Estou enviando um ...**
  - [X] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

## Comportamento esperado
Envio da NFSE para  prefeituras com sistema  IPM Fiscal

## Comportamento Atual
Uncaught Error: Too few arguments to function NFePHP\NFSeIPM\Common\Signer::sign(), 2 passed

## Solução possível
Aparentemente o composer carregou a classe Signer do arquivo oldSigner.php ao invés de carregar o Signer de Signer.php. Como o composer fez isso somente no meu servidor de produção eu simplesmente não consegui entender. Eu não me importo de fazer um PR removendo o oldSigner.php ou até mesmo renomando a classe oldSigner mas achei melhor não mexer antes de trocar uma ideia com você;

## Passos para reproduzir
Eu não entendi exatamente como o composer decidiu que na minha máquina ele ia carregar a classe Signer de Signer.php e em produção carregou o Signer de oldSigner.php então fico devendo os passos pra reproduzir.

## Contexto (Ambiente)
No ambiente em que o erro ocorreu eu removi o arquivo oldSigner.php

**Comment by robmachado** [comment]
Um pergunta você está usado esse pacote ???

**Comment by rafaelmb** [comment]
> 
> 
> Um pergunta você está usado esse pacote ???

Sim

**Comment by robmachado** [comment]
Eu fiz algumas alterações e ajustes nas classes.
Peço sua ajuda para testar ! em seu ambiente de testes.

**Comment by rafaelmb** [comment]
Opa, voltei!

Consegui gerar todas as notas no meu ambiente de testes e movi para produção onde gerei uma NFSE com sucesso. Ficou uma dúvida a respeito do local onde o storage de xml é criado, eu penso que poderia ser um lugar fora da vendor ou pelo menos um lugar configurável mas é fora do escopo desse chamado.

Estou fechando ele, muito obrigado pela ajuda Roberto.
