### ISSUE TITLE
00222 - Assinatura Digital não está íntegra ou nenhuma assinatura foi encontrada no arquivo enviado.

### ISSUE THREAD

**Issue by ivofsouza** [nfephp-org/sped-nfse-ipm#7]
***Estou enviando um 
  - [X] bug
  - [ ] requisição de funcionalidade
  - [ ] requisição de suporte => Por favor, não envie solicitação de suporte aqui, veja a nota no topo deste modelo.

* ** Por favor, conte-nos sobre o seu ambiente: **

  - Versão do leiaute: 1.0

## Comportamento esperado
Deveria retornar os dados do HTML da NFS-e gerada.

## Comportamento Atual
Retorna o Erro:
00222 - Assinatura Digital não está íntegra ou nenhuma assinatura foi encontrada no arquivo enviado.@Assinatura não íntegra! Falha na verificação NFSe_20190110090232.xml NFSe_20190110090232.xml

## Passos para reproduzir
Com um login e senha de acesso ao nfs-e.net e um certificado válido para este login, gerar o XML de exemplo e tentar envia-lo ao ambiente de homologação.

## Contexto (Ambiente)
-> Da forma atual, inviabiliza o uso do sped-nfs-ipm

<! --- Forneça um resumo geral do problema no Título acima ->
00222 - Assinatura Digital não está íntegra ou nenhuma assinatura foi encontrada no arquivo enviado.

**Comment by robmachado** [comment]
Parece ser um problema relativo a alguma estrutura da assinatura ou do calculo do digest.
Como eu não tenho nenhuma NFSe VALIDA (os xml fornecidos pela IPM, parecem não ser válidos) fica muito dificil tentar ajustar a assinatura. 
Veja se consegue um XML assinado válido para fazermos uma engenharia reversa e comparar a construção e cálculos do digest.
